name: compliance

on:
  pull_request:

permissions:
  contents: read

jobs:
  # Reference: ENGSRV-059
  copywrite:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      - uses: hashicorp/setup-copywrite@867a1a2a064a0626db322392806428f7dc59cb3e # v1.1.2
      - run: copywrite headers --plan
      - run: copywrite license --plan
